#!/usr/bin/python
import os, sys

if 'OPENSHIFT_PYTHON_DIR' in os.environ:
	virtenv = os.environ['OPENSHIFT_PYTHON_DIR'] + '/virtenv/'
elif os.path.exists('/var/www/helmgast.se/venv'):
	virtenv = '/var/www/helmgast.se/venv'
	os.chdir('/var/www/helmgast.se') # TODO a bit hacky
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')
try:
  execfile(virtualenv, dict(__file__=virtualenv))
except IOError:
  pass

print >> sys.stderr, os.getcwd()

from ..raconteur import create_app, init_actions

import logging
logging.basicConfig(level=logging.DEBUG,
  format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
 
logging.debug('this is a debug message')

application = create_app()
if 'RACONTEUR_INIT_MODE' in os.environ:
  init_actions(application, os.environ['RACONTEUR_INIT_MODE'])	
  # Clear the init mode flag to avoid running twice accidentaly
  del os.environ['RACONTEUR_INIT_MODE']

logging.debug('this is a 2nd debug message')
