#!/usr/bin/python
import os, sys

# if 'OPENSHIFT_PYTHON_DIR' in os.environ:
# 	virtenv = os.environ['OPENSHIFT_PYTHON_DIR'] + '/virtenv/'
# elif os.path.exists('/var/www/helmgast.se/venv'):
# 	virtenv = '/var/www/helmgast.se/venv/'
# 	os.chdir('/var/www/helmgast.se') # TODO a bit hacky
# 	sys.path.append('/var/www/helmgast.se')
# virtualenv = os.path.join(virtenv, 'bin/activate_this.py')
# try:
#   execfile(virtualenv, dict(__file__=virtualenv))
# except IOError:
#   pass

ALLDIRS = ['/var/www/helmgast.se/venv//lib/python2.7/site-packages']

import site 

# Remember original sys.path.
prev_sys_path = list(sys.path) 

# Add each new site-packages directory.
for directory in ALLDIRS:
  site.addsitedir(directory)

# Reorder sys.path so new directories at the front.
new_sys_path = [] 
for item in list(sys.path): 
    if item not in prev_sys_path: 
        new_sys_path.append(item) 
        sys.path.remove(item) 
sys.path[:0] = new_sys_path 

from raconteur import create_app, init_actions

import logging
logging.basicConfig(level=logging.DEBUG,
  format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
 
logging.debug('this is a debug message')

application = create_app()
if 'RACONTEUR_INIT_MODE' in os.environ:
  init_actions(application, os.environ['RACONTEUR_INIT_MODE'])	
  # Clear the init mode flag to avoid running twice accidentaly
  del os.environ['RACONTEUR_INIT_MODE']

logging.debug('this is a 2nd debug message')
